DROP TABLE IF EXISTS reviews CASCADE;
CREATE TABLE IF NOT EXISTS reviews
(
	id SERIAL PRIMARY KEY,
	tv_show VARCHAR(100) NOT NULL,
    review VARCHAR(100) NOT NULL,
    review_date TIMESTAMP NOT NULL
);
